### ISSUE TITLE
Add license file/specification and release

### ISSUE THREAD

**Issue by dvzrv** [KXStudio/LV2-Extensions#1]
First of all, thanks for tagging this project!
I realized, that I need this now for lv2lint testing purposes when packaging the x42-plugins.

It would be really helpful if you could add one (or many) LICENSE files for the licenses the specific files fall under and clarify which is in use for what file in the README.md or a COPYING.md.

To ease things in the file headers themselves (where applicable) you can also just add a SPDX license identifier comment (based on the Identifier column [here](https://spdx.org/licenses/)) of the form `SPDX-License-Identifier: <Identifier>` AFAIK (see this [example](https://optee.readthedocs.io/en/latest/general/license_headers.html)).

**Comment by dvzrv** [comment]
@falkTX ping :)

**Comment by falkTX** [comment]
Fixed in https://github.com/KXStudio/LV2-Extensions/releases/tag/2020-08-08

**Comment by dvzrv** [comment]
Good stuff, thank you! :)
