### ISSUE TITLE
lilv error on kx-properties.lv2/props.ttl

### ISSUE THREAD

**Issue by jhammen** [KXStudio/LV2-Extensions#2]
encountering message on any app that uses lilv:

error: failed to expand CURIE `opts:Option'
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/kx-properties.lv2/props.ttl'

$ dlocate /usr/lib/lv2/kx-properties.lv2/props.ttl 
kxstudio-lv2-extensions: /usr/lib/lv2/kx-properties.lv2/props.ttl

$ dpkg -s kxstudio-lv2-extensions
Package: kxstudio-lv2-extensions
Status: install ok installed
Priority: extra
Section: devel
Installed-Size: 62
Maintainer: falkTX <falktx@gmail.com>
Architecture: all
Multi-Arch: foreign
Version: 20220214
Recommends: lv2-dev
Description: KXStudio LV2 extensions
 This package contains LV2 extensions developed by the KXStudio Team.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by falkTX** [comment]
Ah, I didnt catch that before.
Fixed now in 58010323797754dc6cd50084d456e5ac2e7c034c

Pushed an update to the kxstudio repos too.
